rootfs-postcommands: Remove spaces before ; in -ROOTFS_..._COMMAND
With spaces in ROOTFS_POSTPROCESS_COMMAND attempts to remove elements
using ROOTFS_POSTPROCESS_COMMAND_remove causes parse failures of the
form:

  bb.pysh.sherrors.ShellSyntaxError: LexToken(COMMA,';',0,0)
  followed by:
    LexToken(TOKEN,'write_image_test_data',0,0)
    LexToken(COMMA,';',0,0)
    LexToken(TOKEN,'set_systemd_default_target',0,0)
    LexToken(COMMA,';',0,0)
    LexToken(TOKEN,'systemd_create_users',0,0)

Removing the spaces between the function name and semicolon allows the
list to parse correctly.

(From OE-Core rev: fd10ee71ddcbcff22e077fa7ac45ac3bcab9a65e)

Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>